apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-sidecar
  labels:
    app: myapp-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-sidecar
  template:
    metadata:
      labels:
        app: myapp-sidecar
    spec:
      containers:
        - name: myapp-sidecar
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}
